# Generated by Django 5.2.3 on 2025-07-11 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JalurPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Jalur Pendaftaran',
                'verbose_name_plural': 'Jalur Pendaftaran',
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('konten', models.TextField()),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='pengumuman/')),
                ('kategori', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('strata', models.CharField(choices=[('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3')], max_length=2)),
                ('deskripsi', models.TextField(blank=True)),
                ('tersedia_jalur_pendaftaran', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
            },
        ),
        migrations.CreateModel(
            name='SistemKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kode', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Sistem Kuliah',
                'verbose_name_plural': 'Sistem Kuliah',
            },
        ),
        migrations.CreateModel(
            name='TataCara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
            ],
            options={
                'verbose_name': 'Tata Cara',
                'verbose_name_plural': 'Tata Cara',
                'ordering': ['nomor'],
            },
        ),
    ]
